---
title: "Chapter 2"
author: "Merrick Howarth"
date: "Oct. 12, 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```


```{r libraries, include=FALSE}

library(tidyverse)
library(sf)
library(tigris)
library(leaflet)
library(tidycensus)
library(censusapi)
library(readxl)

census_api_key("dbcdeeed2f9e907f31811ee78c1f239a2aa77934")
Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")
```

# for assignment may switch to ACS
## 2.1

```{r data}

# geographies
bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_counties <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names)

ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

bay_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()


# PUMS data variables 
pums_vars_2019 <- 
  pums_variables %>%
  filter(year == 2019, survey == "acs5")

# PUMS data 
# ca_pums <- get_pums(
#   variables = c(
#     "PUMA",
#     "GRNTP",
#     "SMOCP",
#     "ADJHSG",
#     "HINCP",
#     "ADJINC"
#   ),
#   state = "CA",
#   year = 2019,
#   survey = "acs5"
# )
# saveRDS(ca_pums,"data/ca_pums.rds")

bay_pums <- readRDS("data/bay_pums.rds")
  # ca_pums %>% 
  # filter(PUMA %in% bay_pumas$PUMACE10)
# saveRDS(bay_pums,"data/bay_pums.rds")




```


```{r ddata manipulatiun}

# adjusting data to 2019 costs and defining burden 

burden_threshold <- 0.3

bay_burden <-
  bay_pums %>% 
  filter(HINCP > 0) %>%
  filter(SPORDER == 1) %>% 
  transmute(
    PUMA,
    weight = WGTP,
    housingcost = ifelse(
      SMOCP > 0,
      SMOCP*12*as.numeric(ADJHSG),
      GRNTP*12*as.numeric(ADJHSG)
    ),
    income = HINCP*as.numeric(ADJINC),
    burden_perc = housingcost/income,
    burden = housingcost - burden_threshold*income
  )



# clarifying burden

bay_burden_pumas <-
  bay_burden %>% 
  mutate(
    burdened = ifelse(
      burden_perc >= burden_threshold,
      weight,
      0
    ),
    excess = ifelse(
      burden < 0,
      burden,
      0
    ),
    burden = ifelse(
      burden > 0,
      burden,
      0
    )
  ) %>% 
  group_by(PUMA) %>% 
  summarize(
    burdened = sum(burdened),
    households = sum(weight),
    burden = sum(burden*weight),
    excess = sum(excess*weight)
  ) %>% 
  mutate(
    burdened_perc = burdened/households
  ) %>% 
  left_join(bay_pumas %>% select(PUMA = PUMACE10)) %>% 
  st_as_sf()

sum(bay_burden_pumas$burdened)/sum(bay_burden_pumas$households)

sum(bay_burden_pumas$burden) %>% prettyNum(",") %>% paste0("$",.)




```


```{r Visualization}

# mpa 1
burden_pal1 <- colorNumeric(
  palette = "Purples",
  domain = bay_burden_pumas$burdened_perc
)

bay_burden_pumas %>% 
  leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    fillColor = ~burden_pal1(burdened_perc),
    fillOpacity = 0.5,
    color = "white",
    weight = 0.5,
    label = ~paste0(round(burdened_perc*100), "% of households paying 30%+ of income on housing"),
    highlightOptions = highlightOptions(
      weight = 2
    )
  ) %>% 
  addLegend(
    pal = burden_pal1,
    values = ~burdened_perc,
    title = "% Cost-burdened<br>households"
  )


# map 2
burden_pal2 <- colorNumeric(
  palette = "Reds",
  domain = bay_burden_pumas$burden/1e6
)

bay_burden_pumas %>% 
  leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    fillColor = ~burden_pal2(burden/1e6),
    fillOpacity = 0.5,
    color = "white",
    weight = 0.5,
    label = ~paste0("$", round(burden/1e6), "M total annual cost burden"),
    highlightOptions = highlightOptions(
      weight = 2
    )
  ) %>% 
  addLegend(
    pal = burden_pal2,
    values = ~burden/1e6,
    title = "Total housing cost<br>burden, in $ millions"
  )


```


## 2.2


```{r pull parcels}

# what shape files will r accept?

sf_parcels_shape <- readRDS("data/sf_parcels_shape.rds")
  # st_read("https://data.sfgov.org/api/geospatial/acdm-wktn?method=export&format=GeoJSON") %>% 
  # filter(active == "true") %>% 
  # select(
  #   apn = blklot,
  #   zoning = zoning_code,
  #   zoning_desc = zoning_district
  # )
# saveRDS(sf_parcels_shape,"data/sf_parcels_shape.rds")



temp <- tempfile()
download.file("https://sfassessor.org/sites/default/files/uploaded/2021.7.28_SF_ASR_Secured_Roll_Data_2020-2021.xlsx",destfile = temp, mode = "wb")

sf_secured <- read_excel(temp, sheet = "Roll Data 2020-2021")
datakey <- read_excel(temp, sheet = "Data Key")
usecode <- read_excel(temp, sheet = "Class Code Only")

unlink(temp)

#datakey %>% select(`DATA NAME`, `FIELD NAME`) %>% as.data.frame()


## combine datas
sf_parcels <-
  sf_parcels_shape %>% 
  left_join(
    sf_secured %>% 
      mutate(
        apn = RP1PRCLID %>% 
          str_replace(" ","")
      )
  )

# check
sum(!is.na(sf_parcels$apn))
sum(!is.na(sf_parcels$RP1PRCLID))
sum(!is.na(sf_parcels$zoning))
sum(!is.na(sf_parcels$ZONE))



```

```{r}
# example

sunset_sample <-
  tracts("CA", "San Francisco", cb = T, progress_bar = F) %>% 
  filter(
    TRACTCE %in% c(
      "030202",
      "030201",
      "032601"
    )
  ) %>% 
  st_transform(4326)

sunset_parcels <- 
  sf_parcels %>% 
  st_centroid() %>% 
  .[sunset_sample, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(sf_parcels %>% select(apn)) %>% 
  st_as_sf() %>% 
  filter(!is.na(RP1PRCLID))

# map parcels of interest

sunset_parcels %>% 
  leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    fillColor = "blue",
    color = "black",
    weight = 0.5,
    label = ~zoning
  )



# condos
duplicate_shapes <- 
  sunset_parcels %>% 
  as.data.frame() %>% 
  filter(duplicated(geometry))

condo_parcels <- 
  sunset_parcels %>% 
  filter(geometry %in% duplicate_shapes$geometry)

condo_parcels %>% 
  leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    fillColor = "blue",
    color = "black",
    weight = 0.5,
    label = ~zoning
  )

sunset_parcels %>%
  st_set_geometry(NULL) %>% 
  group_by(zoning, zoning_desc) %>% 
  summarize(Freq = n())

table(sunset_parcels$RP1CLACDE) %>% 
  as.data.frame() %>% 
  left_join(usecode, by = c("Var1"= "CODE")) %>% 
  select(Freq, DESCRIPTION)



# clean

sunset_parcels_clean <-
  sunset_parcels %>% 
  mutate(
    zoning = case_when(
      zoning == "RM-1|RM-2" ~ "RM-2",
      zoning_desc == "INNER SUNSET NEIGHBORHOOD COMMERCIAL" ~ "INNER SUNSET",
      zoning_desc == "IRVING STREET NEIGHBORHOOD COMMERCIAL DISTRICT" ~ "IRVING ST",
      TRUE ~ zoning
    ),
    UNITS = pmax(UNITS, 1),
    STOREYNO = ifelse(
      !is.na(STOREYNO) & STOREYNO > 0,
      STOREYNO,
      1
    )
  ) %>% 
  filter(zoning != "P") %>% 
  as.data.frame() %>% 
  mutate(geometry = geometry %>% st_as_text()) %>% 
  group_by(geometry) %>% 
  summarize(
    apn = first(apn),
    zoning = first(zoning),
    units = sum(UNITS, na.rm = T),
    floorarea = sum(SQFT, na.rm = T),
    stories = max(STOREYNO, na.rm = T)
  ) %>% 
  ungroup() %>%
  select(-geometry) %>% 
  left_join(sunset_parcels %>% select(apn)) %>% 
  st_as_sf()

 

sf_heights <- st_read("https://data.sfgov.org/resource/h9wh-cg3m.geojson")

sunset_heights <-
  sf_heights %>% 
  st_make_valid() %>% 
  .[sunset_parcels_clean, ]


factpal <- colorFactor(
  c("red","blue"), 
  sunset_heights$height
)

leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = sunset_heights,
    stroke = F,
    fillOpacity = 0.5,
    fillColor = ~factpal(height),
    label = ~height
  ) %>% 
  addPolygons(
    data = sunset_parcels_clean,
    fill = F,
    color = "black",
    weight = 0.5
  )
```


```{r unused area}
## determine areas and unused areas

projection <- "+proj=utm +zone=10 +ellps=GRS80 +datum=NAD83 +units=ft +no_defs"

sunset_parcels_zoning <-
  sunset_parcels_clean %>% 
  st_centroid() %>% 
  st_join(sunset_heights %>% select(gen_hght)) %>% 
  st_drop_geometry() %>% 
  left_join(sunset_parcels_clean %>% select(apn)) %>% 
  st_as_sf() %>% 
  st_transform(projection) %>% 
  mutate(
    lotarea = st_area(.) %>% as.numeric(),
    max_floorarea = case_when(
      zoning == "IRVING ST" ~ lotarea*2.5,
      zoning %in% c("INNER SUNSET","RH-1","RH-2","RH-3","RM-1","RM-2") ~ lotarea*1.8,
      zoning == "RM-3" ~ lotarea*3.6
    ),
    unused_floorarea = pmax(
      max_floorarea - floorarea,
      0
    ),
    max_units = case_when(
      zoning %in% c("INNER SUNSET", "IRVING ST") ~ floor(lotarea/800),
      zoning == "RH-1" ~ 1,
      zoning == "RH-2" ~ 2,
      zoning == "RH-3" ~ 3,
      zoning == "RM-1" ~ pmax(3, floor(lotarea/800)),
      zoning == "RM-2" ~ pmax(3, floor(lotarea/600)),
      zoning == "RM-3" ~ pmax(3, floor(lotarea/400))
    ),
    unused_units = pmax(
      max_units - units,
      0
    ),
    max_height = ifelse(
      is.na(gen_hght),
      40,
      gen_hght %>% as.numeric()
    ),
    max_stories = floor(max_height/11),
    unused_stories = pmax(
      max_stories - stories,
      0
    )
  ) %>% 
  st_transform(4326)



sum(sunset_parcels_zoning$unused_floorarea, na.rm = T)

sum(sunset_parcels_zoning$unused_units, na.rm = T)


# plots
floorarea_pal <- colorBin(
  palette = "Greens",
  bins = c(0,1000,5000,10000,max(sunset_parcels_zoning$unused_floorarea, na.rm = T))
)

leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = sunset_parcels_zoning,
    fillColor = ~floorarea_pal(unused_floorarea),
    fillOpacity = 0.75,
    color = "white",
    weight = 0.5,
    label = ~round(unused_floorarea)
  ) %>% 
  addLegend(
    data = sunset_parcels_zoning,
    pal = floorarea_pal,
    values = ~unused_floorarea,
    title = "Unused Floor Area"
  )


units_pal <- colorBin(
  palette = "Purples",
  bins = c(0,1,5,10,max(sunset_parcels_zoning$unused_units, na.rm = T))
)

leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = sunset_parcels_zoning,
    fillColor = ~units_pal(unused_units),
    fillOpacity = 0.75,
    color = "white",
    weight = 0.5,
    label = ~round(unused_units)
  ) %>% 
  addLegend(
    data = sunset_parcels_zoning,
    pal = units_pal,
    values = ~unused_units,
    title = "Additional Units<br>Allowed"
  )

stories_pal <- colorNumeric(
  palette = "Reds",
  domain = sunset_parcels_zoning$unused_stories
)

leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = sunset_parcels_zoning,
    fillColor = ~stories_pal(unused_stories),
    fillOpacity = 0.75,
    color = "white",
    weight = 0.5,
    label = ~round(unused_stories)
  ) %>% 
  addLegend(
    data = sunset_parcels_zoning,
    pal = stories_pal,
    values = ~unused_stories,
    title = "Additional Stories<br>Allowed"
  )


```



## 2.3 Census-to-parcel disaggregation


```{r}
# census and acs data

acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )

sf_cbgs <- block_groups("CA", "San Francisco", cb = T, progress_bar = F)

potrero_cbg <- 
  sf_cbgs %>% 
  filter(GEOID == "060750614001")


leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = potrero_cbg,
    fill = F
  )



# parcels

sf_parcels_shape <- readRDS("data/sf_parcels_shape.rds")



temp <- tempfile()
download.file("https://sfassessor.org/sites/default/files/uploaded/2020.7.10_SF_ASR_Secured_Roll_Data_2018-2019.xlsx",destfile = temp, mode = "wb")

sf_secured_19 <- read_excel(temp, sheet = "Roll Data 2018-2019")
datakey_19 <- read_excel(temp, sheet = "Data Key")
usecode_19 <- read_excel(temp, sheet = "Class Code Only")



unlink(temp)

potrero_parcels_shape <-
  sf_parcels_shape %>% 
  st_transform(4269) %>% 
  st_centroid() %>% 
  .[potrero_cbg, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(sf_parcels_shape %>% select(apn)) %>% 
  st_as_sf()




# map

leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = potrero_cbg,
    fill = F
  ) %>% 
  addPolygons(
    data = potrero_parcels_shape,
    fillColor = "blue",
    color = "black",
    weight = 0.5,
    label = ~apn
  )



# join

potrero_parcels <-
  potrero_parcels_shape %>% 
  left_join(
    sf_secured_19 %>% 
      mutate(
        apn = RP1PRCLID %>% 
          str_replace(" ","")
      )
  )


table(potrero_parcels$RP1CLACDE) %>% 
  as.data.frame() %>% 
  left_join(usecode_19, by = c("Var1" = "CODE"))


```


```{r joining parcel and acs}

sf_pop_tenure_units <-
  getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "block group:*", 
    regionin = "state:06+county:075",
    vars = "group(B25033)"
  ) %>% 
  mutate(
    cbg =
      paste0(state,county,tract,block_group)
  ) %>% 
  select(!c(GEO_ID,state,county,tract,block_group,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_5yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable) %>% 
  separate(
    label,
    into = c(NA,NA,"tenure","units_in_structure"),
    sep = "!!"
  ) %>% 
  filter(
    cbg == potrero_cbg$GEOID,
    !is.na(units_in_structure),
    estimate > 0
  )



```



```{r}

potrero_parcels_res <-
  potrero_parcels %>% 
  filter(!is.na(RP1CLACDE)) %>% 
  filter(!RP1CLACDE %in% c("E","I","IZ","P","VA1","VCI","VPU","VR","X")) %>% 
  filter(apn != "4260020") %>% 
  mutate(
    UNITS = pmax(UNITS, 1),
    tenure = ifelse(
      is.na(EXEMPTYPE),
      "Renter occupied:",
      "Owner occupied:"
    )
  ) %>% 
  as.data.frame() %>% 
  mutate(geometry = geometry %>% st_as_text()) %>% 
  group_by(geometry) %>% 
  mutate(
    units_in_structure = sum(UNITS, na.rm = T),
    units_in_structure = case_when(
      units_in_structure == 1 ~ "1, detached or attached",
      units_in_structure < 5 ~ "2 to 4",
      TRUE ~ "5 or more"
    )
  ) %>% 
  group_by(tenure, units_in_structure) %>% 
  mutate(
    units_in_bin = sum(UNITS, na.rm = T)
  ) %>% 
  ungroup() %>% 
  select(-geometry) %>% 
  left_join(potrero_parcels %>% select(apn)) %>% 
  st_as_sf()


potrero_parcels_res %>% 
  st_drop_geometry() %>%  
  select(apn, tenure, units_in_structure, UNITS, units_in_bin) %>% 
  head()


```


```{r}

potrero_parcels_census <-
  potrero_parcels_res %>% 
  left_join(
    sf_pop_tenure_units %>% select(-cbg),
    by = c("tenure", "units_in_structure")
  ) %>% 
  mutate(
    pop = UNITS/units_in_bin*estimate
  )


potrero_parcels_census %>% 
  st_set_geometry(NULL) %>% 
  select(apn, tenure, pop) %>% 
  head()


leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = potrero_cbg,
    fill = F
  ) %>% 
  addPolygons(
    data = potrero_parcels_census,
    fillColor = ~ifelse(tenure == "Owner occupied:", "red", "blue"),
    color = ~ifelse(tenure == "Owner occupied:", "red", "blue"),
    weight = 0.5,
    fillOpacity = ~pop/100
  )


# I dont know what that was


```













